name: Kotlin Unit Test
defaults:
  run:
    working-directory: kotlin

on:
  push:
    paths:
      - kotlin/**
      - .github/workflows/kotlin-lint.yml

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "microsoft"
          cache: gradle
      - name: Run Unit Tests
        run: ./gradlew test --no-daemon
      - name: Publishing Unit Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
